name: ci

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Install dependencies
        run: python -m pip install -r requirements-dev.txt
      - name: Install package
        run: python -m pip install .
      - name: Run verify
        run: make verify
